### ISSUE TITLE
add ci/cd : the actual self-updating bit :)

### ISSUE THREAD

**Issue by codeblech** [codeblech/jpgram#10]

**Comment by codeblech** [comment]
added Scheduled tasks on anywhere python.

**Comment by codelif** [comment]
After banging my head for 3 days, I have figured out why instaloader doesn't work on prod server. I recommend getting a bucket of popcorn because this shi- is crazy.

## Prologue 
Instaloader is designed to do something that Instagram is designed to stop, which is, scraping. 

## What went wrong?
Instaloader can retrieve photos from public accounts but only till a limit. That limit is decided by Instagram. After exceeding it, instagram will ask you to login to view furthur posts.

Instaloader is aware of this and to circumvent this you can add an account to instaloader which it will use to retrieve posts. All is well until this point. 

Shit starts to go down when Instagram detects that you are using bots (instaloader in this case), to retrieve posts and flags your account. When it flags your account, you recieve a challenge to solve, without solving them you cannot access any posts.

### What this means for instaloader?
Instaloader is also aware of this prints the links to these challenges to console, which an operator can manually open in a browser, after which instagram will start to behave and you can scrape all you want.

### So how does this relate to instaloader not working on python anywhere?
When this scheduled task is run on python anywhere, instagram immediately flags the IP of python anywhere and sends it a challenge, which it cannot solve automatically.

I tried making an auto-updating github repo to work as an image cache using github action. I encountered the same problem: 
![image](https://github.com/user-attachments/assets/2519b98b-17e6-4ee4-a5d4-63f8022ec86b)

If I don't add a login, in the start a few posts will download but afterwards they will fail like this:
![image](https://github.com/user-attachments/assets/10fd226f-d31f-4419-b8e0-6443278a89f9)

Accessing these links from your laptop doesn't work as these challenges are linked to IP of the GitHub Action servers. So, they need to accessed through them. 


## What can we do?
Not much but maybe... idk. Need to rack some brain cells.

We need to figure out a way to solve these challenges through the IP of the hosting servers. Maybe we can create a proxy server through which we can route our machine's traffic to the hosting server. Seems complex but doable. 

Or someone need to sacrifice their laptop as a server (we can figure out hosting through cloudflare tunnels and shit)

As for the storage problem, I have figured out that Github CDN (githubusercontent.com) allows CORS to other websites, so we can make a seperate repo which will cache the storage and the main server just needs to index it.

## Conclusion
Fk Instagram

**Comment by codeblech** [comment]
First of all, I think GitHub CDN would do the job. In case you wanna implement that, go right ahead with a PR!
As for the scraper blocking by IG... can't think of a solution rn...maybe we should look at how google web crawlers do the scraping. [13ft.io](https://github.com/wasi-master/13ft) pretends to be a google bot to remove paywalls. Apart from, can't think of any other solution rn...

**Comment by codeblech** [comment]
> Fk Instagram  

fr

**Comment by codeblech** [comment]
> Or someone need to sacrifice their laptop as a server (we can figure out hosting through cloudflare tunnels and shit)
naah bro...we'd rather do it manually, weekly atp 😭

**Comment by codelif** [comment]
> First of all, I think GitHub CDN would do the job. In case you wanna implement that, go right ahead with a PR! 

Then could you make a seperate repo like `jpgram-cdn` or `jpgram-lolz` lolz or whatever?

**Comment by codeblech** [comment]
yoooo
what if we write a bash script to.... 👿 ...do this on our own machines. download everything & push to a repo.

**Comment by codelif** [comment]
> yoooo what if we write a bash script to.... 👿 ...do this on our own machines. download everything & push to a repo.

Thats what I had in mind

**Comment by codelif** [comment]
> yoooo what if we write a bash script to....

What if.... what if.... (hear me out), what if we write our server in bash? BASH FTW.....

**Comment by codeblech** [comment]
server? you mean like...apache?

**Comment by codelif** [comment]
> server? you mean like...apache?

I was just kidding lol.

**Comment by codelif** [comment]
> > First of all, I think GitHub CDN would do the job. In case you wanna implement that, go right ahead with a PR!
> 
> Then could you make a seperate repo like `jpgram-cdn` or `jpgram-lolz` lolz or whatever?

This....

**Comment by codeblech** [comment]
> > server? you mean like...apache?
> 
> I was just kidding lol.

that's be crazy tho. chad move. checkmate zuck

**Comment by codeblech** [comment]
> > > First of all, I think GitHub CDN would do the job. In case you wanna implement that, go right ahead with a PR!
> > 
> > 
> > Then could you make a seperate repo like `jpgram-cdn` or `jpgram-lolz` lolz or whatever?
> 
> This....

ye ye
so... i make a separate repo for the cdn, and make you collaborator...is that alright?

**Comment by codelif** [comment]
> > > > First of all, I think GitHub CDN would do the job. In case you wanna implement that, go right ahead with a PR!
> > > 
> > > 
> > > Then could you make a seperate repo like `jpgram-cdn` or `jpgram-lolz` lolz or whatever?
> > 
> > 
> > This....
> 
> ye ye so... i make a separate repo for the cdn, and make you collaborator...is that alright?

collaborator is not necessary. PR are fine.

**Comment by codelif** [comment]
>  how google web crawlers do the scraping. [13ft.io](https://github.com/wasi-master/13ft) pretends to be a google bot to remove paywalls. Apart from, can't think of any other solution rn...

Daaang. That's smart and stupid. So, websites do this for SEO? paywall is just a hoax? damnnn.

**Comment by codelif** [comment]
> That's smart and stupid.

I mean the websites ofc.

**Comment by codeblech** [comment]
> > how google web crawlers do the scraping. [13ft.io](https://github.com/wasi-master/13ft) pretends to be a google bot to remove paywalls. Apart from, can't think of any other solution rn...
> 
> Daaang. That's smart and stupid. So, websites do this for SEO? paywall is just a hoax? damnnn.

ye dude...they let all the web crawlers & creepers touch them however they please

**Comment by codeblech** [comment]
https://github.com/codeblech/jpgram-cdn

**Comment by codelif** [comment]
> > > how google web crawlers do the scraping. [13ft.io](https://github.com/wasi-master/13ft) pretends to be a google bot to remove paywalls. Apart from, can't think of any other solution rn...
> > 
> > 
> > Daaang. That's smart and stupid. So, websites do this for SEO? paywall is just a hoax? damnnn.
> 
> ye dude...they let all the web crawlers & creepers touch them however they please

freaky

**Comment by codeblech** [comment]
creatively named repo
